remote_theme: "mmistakes/minimal-mistakes@4.26.2"

title: "Jesugnon KEKE Portfolio"
description: "Showcasing innovative AI-driven appliances, automation projects, and blog insights."

baseurl: ""
url: "https://kek005.github.io"

author:
  name: "Jesugnon KEKE"
  email: "ancetreseul@example.com"
  avatar: "/assets/images/max_qa_engineer.JPG"
  bio: "QA Engineer and AI Enthusiast passionate about automation and innovative technologies."

social:
  github: "kek005"
  linkedin: "https://www.linkedin.com/in/max-keke-605811229/"

navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"
  - title: "About"
    url: "/about/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

custom_css:
  - /assets/css/custom.css